title:              Mein Blog 
email:              binh-do@hotmail.de
description:        Mein Auslandssemester in Japan 
author:             Binhi
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://thianbinhdo.github.io"

# Social Profiles
github_username:    thianbinhdo
instagram_username: dbiinh

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
